# -*- coding: utf-8 -*-
DISAMBIGUATION_CONSTANTS = {'nrm': ['Page dé frouque', 'Disambig'],
                            'ia': ['Disambiguation'],
                            'bn': ['Disambiguation', 'দ্ব্যর্থতা_নিরসন', 'দ্ব্যর্থতা নিরসন', 'Disambig'],
                            'arc': ['ܕ', 'ܬ.ܐ.', 'Disambig'],
                            'ru': ['АТДы', 'Одноимённые объекты АТД', 'Станции', 'Одноимённые монастыри', 'Воинские части', 'Ждс', 'Islanddis', 'Озёра', 'Одноимённые горы', 'Одноимённые улицы', 'Список тёзок', 'НПы', 'Metrodis', 'Roaddis', 'Одноимённые железнодорожные станции', 'Одноимённые озёра', 'Одноимённые храмы', 'Одноимённые реки', 'Одноимённые острова', 'ЖДС', 'Горы', 'Mondis', 'Mountaindis', 'Surname', 'Военные части', 'Список однофамильцев-тёзок', 'Список однофамильцев', 'Список тёзок-однофамильцев', 'Одноимённые воинские части', 'Одноимённые площади', 'Воинские формирования', 'Неоднозначность', 'Многозначность', 'Одноимённые станции', 'Coorddis', 'Moviedis', 'Нпы', 'Churchdis', 'Lakedis', 'Одноимённые фильмы', 'Одноимённые корабли', 'Placedis', 'Stationdis', 'Militarydis', 'Riverdis', 'Реки', 'Одноимённые памятники', 'Одноименные фильмы', 'Disambiguation', 'Monumdis', 'Одноимённые координаты', 'Острова', 'Одноимённые муниципальные образования', 'Список полных тёзок', 'Disambig', 'Одноимённые населённые пункты', 'Одноимённые горные объекты', 'Одноимённые станции метро', 'Одноимённые НП', 'Неоднозначность2', 'Тёзки-однофамильцы', 'Однофамильцы-тёзки', 'Shipdis'],
                            'ce': ['Цхьа цӀе йолу урамаш', 'Disambiguation', 'Цхьа цӀе йолу меттигаш', 'Цхьа цӀе йолу аьчка некъа агӀонаш', 'Moviedis', 'Disambig', 'Дуккха маьӀнца', 'Цхьа цӀе йолу шагойтарш', 'Surname', 'Placedis', 'Metrodis', 'Roaddis', 'Неоднозначность', 'Цхьатера маьӀна доцуш', 'Доьзал цӀе'],
                            'he': ['פירושונים'],
                            'nds': ['Mehrdüdig_Begreep', 'Mehrdüdig Begreep'],
                            'bar': ['Begriffsklärung', 'Begriffsklearung'],
                            'sc': ['Disambìgua', 'Disambigua'],
                            'ba': ['Disambiguation', 'Күп мәғәнәлелек', 'Неоднозначность', 'Disambig'],
                            'lv': ['Nozīmju atdalīšana', 'Disambig'],
                            'bcl': ['Clarip'],
                            'ang': ['Disambig', 'Geodis'],
                            'vo': ['Telplänov'],
                            'pa': ['Disambig'],
                            'kv': ['Неоднозначность'],
                            'rue': ['Чеперушка'],
                            'cs': ['Rozcestník'],
                            'eu': ['Disambiguation', 'Disambig', 'Argipen'],
                            'fy': ['Neibetsjuttings', 'Tfs', 'Disambig'],
                            'xal': ['Медг-үлг'],
                            'ext': ['Desambiguáncia'],
                            'nn': ['Pekerside', 'Tobokstavforkorting', 'Disambig', 'Fleirtyding', 'Peikar'],
                            'uk': ['Неоднозначність', 'Ще є імена', 'Disambig', 'Багатозначність', 'DisambigN', 'Список однофамільців', 'DisambigG'],
                            'sl': ['Numberdis', 'Razločitev', 'Kazalo ladij', 'Disambig', 'Disambig-ship', 'Priimek', 'Razločitev osebnih imen', 'Disambig-divizija', 'Disambig-brigada', 'Disambig-polk', 'Disambig-korpus', 'Disambig-armada', 'SloPriimek', 'Razločitev cest', 'Kratice', 'Geodis', 'Razločitev-kraj', 'Disambig-unit', 'Georaz'],
                            'eo': ['Apartigilo', 'Disambig'],
                            'mhr': ['Неоднозначность', 'Шуку ончыктымаш-влак', 'Шуко ончыктымаш-влак'],
                            'jv': ['Disambig panggonan', 'Cekakan', 'Disambig', 'Disambig suku', 'Disambig jeneng'],
                            'ht': ['Homonymie', 'Menm non'],
                            'sr': ['Višeznačna odrednica (latinica)', 'Хомограф', 'Disambiguation', 'Вишезначна одредница', 'Вишезначност', 'ВЗО', 'Višeznačna odrednica molekulske formule-lat', 'Взо', 'Disambig', 'Višeznačna-lat', 'Вишезначна', 'Disambig-lat'],
                            'nah': ['Desambiguación'],
                            'scn': ['Disambigua', 'Sigla2', 'Sigla3'],
                            'sah': ['Disambiguation', 'Элбэх суолталаах өйдөбүллэр', 'Неоднозначность', 'Disambig', 'Surname', 'Фамилия'],
                            'hi': ['Disambiguation', 'Disambig', 'बहुवि', 'बहुविकल्पी शब्द'],
                            'mn': ['Disambig', 'Салаа утгатай', 'Салаа'],
                            'ak': ['Disambig'],
                            'als': ['Begriffsklärung', 'Disambig', 'Begriffsklärig'],
                            'ii': ['消含糊', '消除歧义', '消歧义', '消除歧義', 'Disambig', '消歧義', '消除含糊'],
                            'wo': ['Homonymie'],
                            'mg': ['Pejy mitovy anarana', 'Homonymie'],
                            'lmo': ['Desambiguassiú', 'Desambiguazzion', 'Desambiguazion', 'Dezambiguasiù', 'Disambigua', 'Disambig', 'Desambiguació', 'Dezambiguasiú'],
                            'wuu': ['消歧義', '消除歧义', '消除含糊', 'Disambig', '消除歧義', '消歧义', '消含糊'],
                            'mwl': ['Disambig'],
                            'cy': ['Anamrwysedd', 'Gwahaniaethu', 'Disambig'],
                            'vi': ['Định hướng', 'Trang định hướng', 'Dis', 'Disambig', 'Hndis', 'TLAdisambig'],
                            'sk': ['Rozlišovacia stránka'],
                            'ar': ['Disambig', 'توضيح', 'صفحة توضيح'],
                            'gv': ['Reddaghey'],
                            'dv': ['Disambiguation', 'Disambig'],
                            'qu': ["Sut'ichana qillqa"],
                            'io': ['Homonimo'],
                            'zh': ['Disambiguation', '消除歧义', 'Letter disambig', '消岐義', '消岐義頁', 'Disambig', '消除歧義', '消歧义', '消歧義頁', 'Chemdab', 'Disamb', '分歧页', '消歧义页', '消歧義', 'MolFormDisambig', '分歧', 'Dab', '消除含糊', 'Isomerdab', '分歧義', '消含糊', 'Deprecated'],
                            'cv': ['Disambig'],
                            'vep': ['Äiznamoičenduz'],
                            'fiu-vro': ['Linke täpsüstüslehekülile', 'Täpsüstüslehekülg', 'Disambig'],
                            'hu': ['Egyért-redir', 'Egyértelműsítő lap', 'Egyértelműsítő', 'Egyért', 'Disambig', 'Egyert'],
                            'mi': ['Disambig'],
                            'os': ['Неоднозначность', 'Disambig'],
                            'ml': ['വിവക്ഷകൾ', 'Disambig', 'നാനാര്\u200dത്ഥം', 'നാനാർത്ഥങ്ങൾ'],
                            'simple': ['Callsigndis', 'School disambiguation', 'Letter-NumberCombDisambig', 'Numberdis', 'Disamb-cleanup', 'Schooldis', 'Letter disambiguation', 'LatinNameDisambig', 'Biology disambiguation', 'Taxonomic authority disambiguation', 'Hndis', 'Dab-cleanup', 'Shortcut disambig', 'Disambiguation page', 'WP-disambig', 'Hospital disambiguation', 'Disambig-Chinese-char-title', 'Chinese title disambiguation', 'Cleanup disambig', 'Letter disambig', 'Mathematics disambiguation', 'Species Latin name abbreviation disambiguation', 'Taxonomy disambiguation', 'MolFormDisambig', 'CJKVdab', 'Chemistry disambiguation', 'Mathematical disambiguation', 'Mil-unit-dis', 'Airport disambiguation', 'Molecular formula disambiguation', 'Numdab', 'CleanupDisambig', 'Disambiguation-cleanup', 'Bio-dab', 'Disamb', 'Species Latin name disambiguation', 'Genus disambiguation', 'Dabclean', 'Dab', 'Synagogue disambiguation', 'Personal name disambiguation cleanup', 'Mathdab', 'Hndisambig', 'Wikipedia disambiguation', 'Disambig-CU', 'Disambig-cleanup', 'Disambiguation', 'WP Disambig', 'Call sign disambiguation', 'Disambiguation cleanup', 'Geo-dis', 'Geodab', 'Disambig', 'Airport disambig', 'DAB', 'SpeciesLatinNameDisambig', 'NA Broadcast List', 'WP disambig', 'Hndab', 'Geodis', 'Dbig', 'Letter-NumberCombdisambig', 'Hndis-cleanup'],
                            'pl': ['Ujednoznacznienie', 'Disambig'],
                            'is': ['Tveggja stafa aðgreining', 'Aðgreining'],
                            'ch': ['Disambig'],
                            'ms': ['Nyahkekaburan', 'Disambig'],
                            'ie': ['Disambig'],
                            'yi': ['באדייטן'],
                            'ast': ['Dixebra'],
                            'oc': ['Sigla', 'Omonimia', 'Paronimia', 'Omonimia2', 'Siglas n letras'],
                            'tg': ['Ибҳомзудоӣ', 'Disambig'],
                            'nds-nl': ['Dv'],
                            'srn': ['Dp', 'Doorverwijspagina'],
                            'fa': ['ابهام\u200cزدایی-جغرافیا', 'رفع ابهام', 'ابهام\u200cزدایی', 'ابهام زدایی', 'ابهام\u200cزدائی'],
                            'la': ['Discretiva'],
                            'id': ['Disambig karya', 'Disambig-cleanup', 'Disambig nama', 'Disingkat', 'Disambig sekolah', 'Disambig', 'Disambig suku', 'Hndis', 'Disambig sejarah', 'Disambig bandara', 'Disambig tempat', 'Disambig tempat indo', 'Disambig indo1', 'Disambiguasi', 'Disambig olahraga'],
                            'sv': ['3Bgren', 'Trebokstavsförgrening', 'Disambiguation', 'Namngrensida', 'Trebokstavsförkortning', '3LC', 'Gaffel', 'Disambig', '4LA', 'Fyrbokstavsförgrening', 'Betydelselista', 'Hndis', '4LC', 'Förnamn', 'Grensida', 'Dab', 'Efternamn', 'Gren', 'Namnförgrening', 'Förgreningssida', 'Ortnamn', 'Flertydig', 'Förgrening', 'Robotskapad förgrening', 'TLAdisambig', '3LA'],
                            'br': ['Project:Liammoù_ouzh_ar_pajennoù_disheñvelaat', "Disheñvelout lec'hanvioù", 'Disheñvelout anvioù-badez', 'Disheñvelout', 'Disheñvelout anvioù-tud'],
                            'ka': ['მრავმნიშ', 'Disambig', 'მრავალმნიშვნელოვანი'],
                            'uz': ['Disambig'],
                            'szl': ['Disambig'],
                            'bjn': ['Disambig'],
                            'no': ['Etternavn', 'Tobokstavsforkortelse', 'Disambiguation', 'Pekerside', 'Trebokstavsforkortelse', 'Disambig', 'Geodis', 'Flertydig', 'Hndis', 'Peker', 'Disamb'],
                            'en': ['SIA', 'Mountainindex', 'Letter disambig', 'Hospitaldis', 'Geodis', 'Hndis', 'Fish-dab', 'Numberdis', 'Hndis-cleanup', 'Roaddis', 'Disambig-Chinese-char-title', 'POWdis', 'Schooldis', 'Disambig-cleanup', 'Mathdab', 'Disambiguation', 'Dab', 'Given name', 'Disambig', 'Surname', 'Shipindex', 'NA Broadcast List'],
                            'arz': ['توضيح'],
                            'kab': ['Asefham'],
                            'bug': ['Disambig'],
                            'tl': ['Paglilinaw', 'Disambig'],
                            'be': ['Неадназначнасць'],
                            'gn': ['Disambig'],
                            'kn': ['ದ್ವಂದ್ವ ನಿವಾರಣೆ'],
                            'myv': ['Смустень коряс явома'],
                            'fi': ['Täsmennyssivu', 'Täsmennyssivu/sukunimi', 'Disambig'],
                            'lij': ['Disambigua'],
                            'ln': ['Bokokani', 'Homonymie'],
                            'mr': ['Disambiguation', 'नि:संदिग्धीकरण'],
                            'pfl': ['BKL'],
                            'war': ['Pansayod'],
                            'ace': ['Disambig'],
                            'lt': ['Daugiareikšmis', 'Nuorodiniai straipsniai', 'Kodai', 'Disambig', 'Nuorodinis', 'Valdovas-disambig', 'Pavardė'],
                            'de': ['Begriffsklärung'],
                            'da': ['Begriffsklärung', 'Navn', 'Disambig', 'Flertydig'],
                            'mdf': ['Disambiguation', 'Фкялемса ошкужот', 'Moviedis', 'Disambig', 'Surname', 'Фкялемса фильпт', 'Placedis', 'Фкялемса кит', 'Фкялемса метро валгамвастт', 'Атянь лем', 'Metrodis', 'Roaddis', 'Аф фкя смузь', 'Лама смусть'],
                            'csb': ['Disambig', 'Starnë_ùjednoznacznieniô'],
                            'te': ['వివరమైన అయోమయ నివృత్తి', 'అయోమయ నివృత్తి'],
                            'gan': ['消含糊', '消除歧义', '消歧义', '消除歧義', 'Disambig', '消歧義', '消除含糊'],
                            'xmf': ['მრავალმნიშვნელოვანი'],
                            'es': ['Des', 'Desambig', 'Desambiguacion', 'Disambig', 'Desambiguación'],
                            'li': ['Vp', 'Verdudeliking', 'Disambig', 'Verdudelikingpazjena'],
                            'frr': ['Muardüüdag artiikel', 'Muar Meeningen'],
                            'fur': ['Disambigua', 'Disambig', 'Disambiguazion'],
                            'hr': ['Nova razdvojba', 'Preusmjerenje u razdvojbu', 'Razdvojba'],
                            'nap': ['Disambigua'],
                            'vec': ['Disanbigua', 'Disambigua', 'Dixanbigua'],
                            'tt': ['Күп мәгънәләр', 'Күп мәгънәле'],
                            'ko': ['분류 동음이의', '동음이의', 'Disambig', '동음이의어', '동명이인'],
                            'mai': ['Disambig'],
                            'map-bms': ['Disambig'],
                            'ur': ['Disambig'],
                            'tr': ['Kısaltmalar (anlam ayrımı)', 'Kişi adları (anlam ayrımı)', 'Yerleşim anlam ayrımı', 'Anlam ayrımı', 'Disambig', 'Anlam ayrım', 'Sayılar (anlam ayrımı)', 'Coğrafya (anlam ayrımı)'],
                            'hsb': ['Wjacezmyslnosć'],
                            'af': ['Dubbelsinnig', 'Disambig'],
                            'pms': ['Gestion dij sinònim'],
                            'tpi': ['Disambig'],
                            'rm': ['Sclerir noziun'],
                            'ro': ['Dezamb', 'Persoane omonime', 'DezNume', 'Dezambiguizare comitate SUA', 'Dezambiguizare', 'DezGeo', 'Disambig', 'Hndis', 'Dez'],
                            'cu': ['Мъногосъмꙑслиѥ', 'Мъногосъмꙑ́слиѥ', 'Disambig', 'Мъногосъмыслиѥ'],
                            'sw': ['Maana'],
                            'ckb': ['ڕوونکردنەوە'],
                            'udm': ['Disambiguation', 'Неоднозначность', 'Disambig', 'Многозначность'],
                            'nv': ['Ałtsʼáʼáztiin'],
                            'ca': ['Acrònim', 'Onomàstica', 'Desambigua', 'DesambigCurta', 'Disambig', 'Biografies', 'Desambiguació'],
                            'zea': ['Doorverwijspagina'],
                            'th': ['แก้ความกำกวม', 'คำกำกวม', 'Disambig', 'แก้กำกวม'],
                            'lbe': ['Неоднозначность'],
                            'nl': ['Dp', 'Dp-intro', 'Disambig', 'DP', 'Dpintro'],
                            'to': ['Fakaʻuhingakehe'],
                            'zh-yue': ['Disambig', '搞清楚'],
                            'ne': ['Disambig'],
                            'mt': ['Diżambigwazzjoni', 'Diżambig'],
                            'bg': ['Пояснение', 'Disambig'],
                            'hif': ['Disambig'],
                            'eml': ['Disambigua'],
                            'crh': ['Disambig', 'Çoq manalı'],
                            'diq': ['Disambig'],
                            'zh-min-nan': ['KhPI', 'Khu-pia̍t-iah', 'Khu-pia̍t-ia̍h', 'Disambig'],
                            'ty': ['Homonymie'],
                            'mzn': ['ابهام\u200cزدایی'],
                            'sh': ['Razdvojba', 'Višeznačnost', 'VZO', 'Višeznačna odrednica', 'Disambig', 'Razvrstavanje', 'Radzvojba', 'Homograf', 'Čvor'],
                            'sco': ['Disambig', 'Geodis'],
                            'dsb': ['Wěcejwóznamowosć', 'Rozjasnjenje zapśimjeśow'],
                            'gd': ['Soilleireachadh'],
                            'kbd': ['Disambig'],
                            'sd': ['Disambig'],
                            'or': ['DAB', 'Disambiguation', 'Numberdis', 'Dab', 'ବହୁବିକଳ୍ପ', 'Disambig', 'Disamb'],
                            'pap': ['Disambig'],
                            'av': ['Неоднозначность'],
                            'hy': ['Բազմիմաստ', 'Բազմանշանակություն', 'Բի', 'Բազմանշանակ', 'Disambig', 'Բազմիմաստություն', 'Երկիմաստ'],
                            'sa': ['Disambig'],
                            'ja': ['Aimai'],
                            'kl': ['Disambig', 'Flertydig', 'Qulequtaqatigiit'],
                            'as': ['দ্ব্যর্থতা_নিরসন'],
                            'bat-smg': ['Daugiareikšmis', 'Disambig'],
                            'vls': ['Db', 'Disambig', 'Doorverwijspagina'],
                            'stq': ['Begriepskläärenge'],
                            'pdc': ['Begriffsklärung'],
                            'it': ['Disambigua'],
                            'cbk-zam': ['Desambiguación'],
                            'an': ['Desambig', 'Disambig', 'Desambigazión', 'Desambigación'],
                            'el': ['Αποσαφήνιση', 'Αποσαφ', 'Disambig'],
                            'kk': ['Айрық'],
                            'ay': ['Desambiguación'],
                            'sq': ['Kthjellim'],
                            'ff': ['Homonymie'],
                            'wa': ['Omonimeye'],
                            'frp': ['Disambig', 'Homonimia', 'Homonimos'],
                            'gl': ['Disambig', 'Homónimos'],
                            'fr': ['Communes françaises homonymes', 'Unités homonymes', 'Batailles homonymes', "Homonymie d'îles", 'Paronymie', 'Homonymie de route', 'Internationalisation', "Homonymie d'établissements scolaires ou universitaires", 'Cantons homonymes', 'Homonymie bateau', 'Homonymie de comtés', 'Gouvernements homonymes', 'Homonymie de monument', 'Toponymie', 'Isomérie', 'Homonymie de nom romain', 'Titres homonymes', 'Saints homonymes', 'Guerres homonymes', "Bandeau standard pour page d'homonymie", 'Homonymie de clubs sportifs', 'Homonymie', 'Villes homonymes', 'Patronymie', 'Arrondissements homonymes', 'Films homonymes', 'Patronyme basque', 'Patronyme italien', 'Homonymie dynastique', 'Homonymie vidéoludique', 'Personnes homonymes', 'Homonymie de parti politique', 'Patronyme', 'Homonymie édifice religieux', 'Édifices religieux homonymes'],
                            'glk': ['ابهام\u200cزدایی'],
                            'mo': ['Dezambiguizare', 'Disambig'],
                            'bs': ['Čvor'],
                            'lb': ['Homonymie Familljennumm', 'Homonymie', 'Homonymie Persounen', 'Disambig', 'Homonymie Ofkierzungen'],
                            'bpy': ['দ্ব্যর্থতা_নিরসন', 'সন্দই চুম'],
                            'kw': ['Klerheans'],
                            'yo': ['Disambig', 'Ìṣojútùú'],
                            'fo': ['Fleiri týdningar', 'Disambig'],
                            'ga': ['Idirdhealú', '{{ns:project}}:Naisc_go_leathanaigh_idirdhealaithe'],
                            'bm': ['Homonymie'],
                            'ilo': ['Disambig'],
                            'kaa': ['Disambig-cleanup', 'Hospitaldis', 'Schooldis', 'Numberdis', 'Disamb-cleanup', 'Disambiguation', 'Bio-dab', 'Disambig', 'POWdis', 'Surname', 'Hndis', 'SIA', 'Disamb', 'Mountainindex', 'Dab', 'Given name', 'Roaddis', 'Shipindex', 'Geodis', 'Mathdab', 'Hndisambig', 'Diasmbig', 'Hndis-cleanup'],
                            'ku': ['Cudakirin', 'Disambig'],
                            'krc': ['Disambiguation', 'Кёб магъаналы', 'Disambig'],
                            'roa-tara': ['Disambigua', 'Disambig', 'Sigla2', 'Disambigue', 'Sigla3'],
                            'ltg': ['Disambiguation', 'Zeimeibu škiršona', 'Disambig'],
                            'mrj': ['Disambig'],
                            'mk': ['ГеоПојас', 'Појаснување', 'Disambig', 'Geodis', 'ЧИ-Појаснување', 'Hndis'],
                            'lad': ['Desambiguación'],
                            'gag': ['Kısaltmalar (anlam ayrımı)', 'Anlam ayrımı', 'Disambig', 'Anlam ayrım'],
                            'pam': ['Callsigndis', 'Hospitaldis', 'Letter-NumberCombDisambig', 'Numberdis', 'Schooldis', 'Disamb-cleanup', 'Numdab', 'CleanupDisambig', 'LatinNameDisambig', 'Bio-dab', 'Roadab', 'Hurricane disambig', 'Church disambig', 'Hndis', 'Dab-cleanup', 'Disamb', 'Dabclean', 'Dab', 'Shortcut disambig', 'WP-disambig', 'Roaddis', 'Cleanup-disambig', 'Mathdab', 'Hndisambig', 'Roadis', 'Shorcut disambig', 'Disambig-CU', 'Disambig-Chinese-char-title', 'Disambig-cleanup', 'Disambiguation', 'WP Disambig', 'Cleanup disambig', 'Letter disambig', 'Geo-dis', 'Geodab', 'Disambig', 'Airport disambig', 'Pamipalino', 'Namedab', 'MolFormDisambig', 'CJKVdab', 'NA Broadcast List', 'WP disambig', 'Hndab', 'Geodis', 'Hndis-cleanup'],
                            'rmy': ['Dezambiguizare'],
                            'az': ['Dəqiqləşdirmə'],
                            'am': ['መንታ'],
                            'ceb': ['Disambig', 'Giklaro'],
                            'ksh': ['Disambig'],
                            'ab': ['Неоднозначность'],
                            'ss': ['Disambig'],
                            'si': ['Callsigndis', 'Letter-NumberCombDisambig', 'Numberdis', 'Schooldis', 'Disamb-cleanup', 'Numdab', 'CleanupDisambig', 'LatinNameDisambig', 'Biology disambiguation', 'Bio-dab', 'Hndis', 'Dab-cleanup', 'Disamb', 'Species Latin name disambiguation', 'Genus disambiguation', 'Dabclean', 'Dab', 'Shortcut disambig', 'WP-disambig', 'Hospital disambiguation', 'Mathdab', 'Hndisambig', 'Disambig-CU', 'Disambig-Chinese-char-title', 'Disambig-cleanup', 'Disambiguation', 'WP Disambig', 'Cleanup disambig', 'Letter disambig', 'Disambiguation cleanup', 'Geo-dis', 'Geodab', 'Disambig', 'Airport disambig', 'Species Latin name abbreviation disambiguation', 'Taxonomy disambiguation', 'MolFormDisambig', 'CJKVdab', 'SpeciesLatinNameDisambig', 'NA Broadcast List', 'WP disambig', 'Hndab', 'Chemistry disambiguation', 'Geodis', 'වක්\u200dරෝත්තිහරණ', 'Letter-NumberCombdisambig', 'Hndis-cleanup'],
                            'pt': ['Disambiguation', '!Desambiguação', 'Desambig-ini', 'Desambiguação', 'Desambig', 'Disambig', 'Desambig-wikcionário'],
                            'ta': ['பக்கவழி நெறிப்படுத்தல்'],
                            'za': ['消含糊', '消除歧义', '消歧义', '消除歧義', 'Disambig', '消歧義', '消除含糊'],
                            'su': ['Project:Tumbu_ka_kaca_disambiguasi', 'Disambig']}